### ISSUE TITLE
Installer with Proxy

### ISSUE THREAD

**Issue by xtexChooser** [Stefan0436/Cyan#3]
> Update: MultiMC support request canceled

Network in China is not very well(in sometimes, aka as The Great Firewall), but I can use proxy to open many websites(include github) but Cyan Installer is not using the proxy(in Windows Settings)
Image: background: in browser, open correctly, foreground: installer, error without proxy
![image](https://user-images.githubusercontent.com/46394906/129432338-773ec84a-f8c2-4d6c-bd3f-3c57618ea502.png)
Image: in windows settings
![image](https://user-images.githubusercontent.com/46394906/129432347-390e2a49-5b5a-4c17-8598-abc4cc0ce224.png)

**Comment by SkySwimmer** [comment]
That's a tricky one, an SSL Exception is often caused when a website's certificate could not be verified, i'll create a command line option to force KickStart to ignore SSL.

**Comment by SkySwimmer** [comment]
You could try starting the installer from windows CMD, adding `-Dhttp.proxyHost=yourproxy.somedomain` and `-Dhttp.proxyPort=proxyport` to force Java to use your proxy, i do not know if this will work, because i don't have a proxy myself.

**Comment by SkySwimmer** [comment]
The full command would be: `javaw -Dhttp.proxyHost=<proxy ip> -Dhttp.proxyPort=<proxy pory> -jar <version>-cyan-1.0.0.A14-installer.jar`
