### ISSUE TITLE
Regarding the problem that Chinese players cannot connect

### ISSUE THREAD

**Issue by purpleseaweed** [Stefan0436/Cyan#6]
Hello!I am a loyal player of Minecraft,I from China,I saw your Cyan client on the mcmod website (China)，But this client cannot be installed in China,(Website can go in),Is there a Chinese mirror that can solve the problem that cannot be installed?(English is not good,pure google translation)

**Comment by SkySwimmer** [comment]
There are no mirrors yet, but i will add support for it in the next build.

It might take a while before any mirrors exist, but i will at least create a support system for it.

\- Sky Swimmer

**Comment by SkySwimmer** [comment]
I have created a new issue specifically for mirror support [here](https://github.com/Stefan0436/Cyan/issues/8).

Thanks for reporting!

\- Sky Swimmer
